name: FearTheReaper
version: 0.1.0-b000
main: com.herocraftonline.fearthereaper.FearTheReaper
author: Sleaker
commands:
  graveyard:
    description: Graveyard Commands
    usage: /<command> <list | add | delete | tp | closest>
    aliases: ['gy']